"""
Cogniflow Orchestrator v3.0 — Hook installation (REQ-HOOK).

Generates:
  {pipeline_dir}/CLAUDE.md           — shared project context (CLI injects natively)
  {pipeline_dir}/.claude/settings.json — hook registrations
  {pipeline_dir}/.claude/hooks/      — copies of the three hook scripts

Also provides the `cogniflow hooks install` command logic.
"""
from __future__ import annotations

import json
import os
import shutil
import sys
from pathlib import Path
from typing import Any


# Absolute path to the hook_scripts directory in this package
_HOOK_SCRIPTS_DIR = Path(__file__).parent / "hook_scripts"


def generate_claude_md(pipeline_dir: Path, spec: dict[str, Any]) -> None:
    """
    Write CLAUDE.md to the pipeline directory (REQ-PIPELINE-005).
    Content is injected natively by the Claude CLI into every agent session.
    The orchestrator MUST NOT duplicate this content in 04_context.md.
    """
    name        = spec.get("name", "pipeline")
    description = spec.get("description", "")
    agents      = spec.get("agents", [])
    domain_tags = spec.get("tags", {}).get("domain", [])
    struct_tags = (
        "decision, revision, superseded, open-question, proposal, rejection, "
        "constraint, acknowledgement, escalation, clarification"
    )

    agent_lines = "\n".join(
        f"- {a['id']:15s}: {a.get('description', a['id'])}"
        for a in agents
    )
    domain_str = ", ".join(domain_tags) if domain_tags else "(none defined)"

    content = f"""# CLAUDE.md — {name}
# Generated by Cogniflow Orchestrator v3.0

## Project context
{description or 'No description provided.'}

## Agent roster
{agent_lines}

## Tag vocabulary
Structural: {struct_tags}
Domain    : {domain_str}

## Shared workspace
Artifacts are stored in: .state/shared/
ARTIFACT_INDEX.json lists current versions of all shared files.

## Coordination notes
- You are part of a cyclic multi-agent system.
- Every response MUST end with the required JSON routing block (see your system prompt).
- Emit status:done only when your convergence checklist is fully satisfied.
- Never re-open closed decisions. Never route to agents not listed in your contacts.
"""
    out = pipeline_dir / "CLAUDE.md"
    out.write_text(content, encoding="utf-8")


def install_hooks(pipeline_dir: Path, config_claude_bin: str | None = None) -> None:
    """
    Generate .claude/settings.json and copy hook scripts (REQ-HOOK-001/002).
    Called by `python cli.py hooks install {pipeline_dir}`.
    """
    claude_dir  = pipeline_dir / ".claude"
    hooks_dir   = claude_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    python_exe  = sys.executable
    hooks_abs   = hooks_dir.resolve()

    settings = {
        "hooks": {
            "PostToolUse": [{
                "matcher": ".*",
                "hooks": [{
                    "type": "command",
                    "command": f"{python_exe} {hooks_abs / 'post_tool_event.py'}",
                }],
            }],
            "Stop": [{
                "matcher": "",
                "hooks": [{
                    "type": "command",
                    "command": f"{python_exe} {hooks_abs / 'agent_stop_event.py'}",
                }],
            }],
            "StopFailure": [{
                "matcher": "",
                "hooks": [{
                    "type": "command",
                    "command": f"{python_exe} {hooks_abs / 'agent_stop_failure_event.py'}",
                }],
            }],
        }
    }

    (claude_dir / "settings.json").write_text(
        json.dumps(settings, indent=2), encoding="utf-8"
    )

    # Copy hook scripts
    for script_name in (
        "post_tool_event.py",
        "agent_stop_event.py",
        "agent_stop_failure_event.py",
    ):
        src = _HOOK_SCRIPTS_DIR / script_name
        dst = hooks_dir / script_name
        if src.exists():
            shutil.copy2(src, dst)
        else:
            # Fallback: generate minimal stubs
            _write_stub(dst, script_name)

    print(f"  ✓ .claude/settings.json written")
    print(f"  ✓ Hook scripts installed to {hooks_dir}")


def _write_stub(dst: Path, name: str) -> None:
    """Write a minimal stub if the real hook script is not found."""
    dst.write_text(
        f"#!/usr/bin/env python3\n"
        f"# Stub: {name}\n"
        f"# Install cogniflow package to get the full hook scripts.\n"
        f"import sys; sys.exit(0)\n",
        encoding="utf-8",
    )
